### ISSUE TITLE
Which maven repository I can find it and download it?

### ISSUE THREAD

**Issue by wahyd4** [garrettheel/moco-maven-plugin#1]
Do I need add a maven repository in my pom file?

**Comment by garrettheel** [comment]
Hey, I haven't submitted the artifact to a repository yet as it's only new. I'll look into getting it added to the sonatype repo so it lives alongside Moco.

**Comment by wahyd4** [comment]
Thanks.
Waiting for it be done.

**Comment by garrettheel** [comment]
Raised JIRA at Sonatype - https://issues.sonatype.org/browse/OSSRH-5740.

**Comment by wahyd4** [comment]
It seems like you can deploy it to oss repo now.

**Comment by garrettheel** [comment]
All done - have deployed the 1.0-SNAPSHOT to the repository and updated README with an example.

**Comment by wahyd4** [comment]
Hi, could you please update the moco version to 0.6.4 ? Cause I've used the newest features of moco while the moco  version(0.6.3) in moco-maven-plugin doesn't contain those.
The good thing is the moco author just updated it right now.

Thank you.

**Comment by garrettheel** [comment]
Sure thing, should be done now :)
