### ISSUE TITLE
moco-maven-plugin release request

### ISSUE THREAD

**Issue by goghvanmr** [garrettheel/moco-maven-plugin#2]
Hello, 

We found that, the plugin in the oss repo (and the maven central) is not the newest version. Could please update it?

Thank you very much.

Yi

**Comment by garrettheel** [comment]
Hi Yi,

You're correct! I haven't gotten around to publishing the 0.8 via a release yet (hope to do that in the next week), but for now I've updated the 1.0-SNAPSHOT to the latest version.

Hope that helps

**Comment by fedcuit** [comment]
Hi there,

I'm erdong and i am working together with Yi on the same project, we are trying to use moco-maven-plugin to setup a  mocking server. I noticed you just committed some code to match the latest moco version which has the proxy functionality, we are heavily depends on this feature, it would be very helpful if you can help to update the latest commit into maven repo.

Big Thanks,

**Comment by garrettheel** [comment]
Hey guys - I've released 0.8.0 (based on moco 0.8) to central repo. Hope this solves your issues.

``` xml
<dependency>
  <groupId>com.garrettheel</groupId>
  <artifactId>moco-maven-plugin</artifactId>
  <version>0.8.0</version>
</dependency>
```

**Comment by fedcuit** [comment]
Thank you very much.  

Erdong Feng / 冯 尔东
Consultant  

## ThoughtWorks

Mobile: +86 13811816914
Email: edfeng@thoughtworks.com (mailto:yingliu@thoughtworks.com)
MSN: fedcuit@gmail.com (mailto:fedcuit@gmail.com)

## Skype: fedcuit

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by goghvanmr** [comment]
Thanks man, 

Just for your information, there's a bug in moco 0.8 about the proxy feature, which causes failures on certain websites. I opened a pull request: https://github.com/dreamhead/moco/pull/25 

Yi
