### ISSUE TITLE
Can you update the moco version to 0.9.1-snapshot?

### ISSUE THREAD

**Issue by wahyd4** [garrettheel/moco-maven-plugin#3]
According to the words from moco's author he just fixed a bug to solve moco can't process two continuous HTTP requests.

Can you update the moco plugin version accordingly?

Thank you.

**Comment by garrettheel** [comment]
Hey, I've uploaded 0.9 release and 0.9.1-SNAPSHOT so should be good to go. Let me know if you have any problems.

Cheers,
Garrett
