### ISSUE TITLE
Update moco to latest version

### ISSUE THREAD

**Issue by htynkn** [garrettheel/moco-maven-plugin#4]
Hi GarrettHeel,

Thanks for this outstanding maven plugin.It's very useful.

I see the last commit of this project is in the year 2013 and the version of moco is 0.9.1-snapshot.

But now moco is already 0.9.2.

Could you update the moco version to the latest version?

Many thanks.

**Comment by garrettheel** [comment]
Hi Huang,

Sure thing, I've just pushed `0.9.2` up to central which I tested against Moco 0.9.2. Note that you can usually use this plugin with newer versions of Moco provided that the public APIs I use don't change too much (which they did for this update).

Cheers!
Garrett

**Comment by htynkn** [comment]
Thank you very much. ^_^
