### ISSUE TITLE
 An API incompatibility was encountered

### ISSUE THREAD

**Issue by hanrw** [garrettheel/moco-maven-plugin#5]
[ERROR] Failed to execute goal com.garrettheel:moco-maven-plugin:0.9.2:start (start-moco) on project wcs-ferguson-service: Execution start-moco of goal com.garrettheel:moco-maven-plugin:0.9.2:start failed: An API incompatibility was encountered while executing com.garrettheel:moco-maven-plugin:0.9.2:start: java.lang.NoSuchMethodError: com.github.dreamhead.moco.bootstrap.StartArgs.<init>(Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/github/dreamhead/moco/bootstrap/HttpsArg;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.garrettheel:moco-maven-plugin:0.9.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/.m2/repository/com/garrettheel/moco-maven-plugin/0.9.2/moco-maven-plugin-0.9.2.jar
[ERROR] urls[1] = file:/D:/.m2/repository/com/github/dreamhead/moco-runner/0.10.0-SNAPSHOT/moco-runner-0.10.0-SNAPSHOT.jar
[ERROR] urls[2] = file:/D:/.m2/repository/com/google/guava/guava/17.0/guava-17.0.jar
[ERROR] urls[3] = file:/D:/.m2/repository/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.jar
[ERROR] urls[4] = file:/D:/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[ERROR] urls[5] = file:/D:/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[ERROR] urls[6] = file:/D:/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
[ERROR] urls[7] = file:/D:/.m2/repository/com/github/dreamhead/moco-core/0.10.0-SNAPSHOT/moco-core-0.10.0-SNAPSHOT.jar
[ERROR] urls[8] = file:/D:/.m2/repository/org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar
[ERROR] urls[9] = file:/D:/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[10] = file:/D:/.m2/repository/io/netty/netty-codec-http/4.0.23.Final/netty-codec-http-4.0.23.Final.jar
[ERROR] urls[11] = file:/D:/.m2/repository/io/netty/netty-codec/4.0.23.Final/netty-codec-4.0.23.Final.jar
[ERROR] urls[12] = file:/D:/.m2/repository/io/netty/netty-transport/4.0.23.Final/netty-transport-4.0.23.Final.jar
[ERROR] urls[13] = file:/D:/.m2/repository/io/netty/netty-handler/4.0.23.Final/netty-handler-4.0.23.Final.jar
[ERROR] urls[14] = file:/D:/.m2/repository/io/netty/netty-buffer/4.0.23.Final/netty-buffer-4.0.23.Final.jar
[ERROR] urls[15] = file:/D:/.m2/repository/io/netty/netty-common/4.0.23.Final/netty-common-4.0.23.Final.jar
[ERROR] urls[16] = file:/D:/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[17] = file:/D:/.m2/repository/com/jayway/jsonpath/json-path/0.9.1/json-path-0.9.1.jar
[ERROR] urls[18] = file:/D:/.m2/repository/net/minidev/json-smart/1.2/json-smart-1.2.jar
[ERROR] urls[19] = file:/D:/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar
[ERROR] urls[20] = file:/D:/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar
[ERROR] urls[21] = file:/D:/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
[ERROR] urls[22] = file:/D:/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.2/jackson-databind-2.4.2.jar
[ERROR] urls[23] = file:/D:/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.4.0/jackson-annotations-2.4.0.jar
[ERROR] urls[24] = file:/D:/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.2/jackson-core-2.4.2.jar
[ERROR] urls[25] = file:/D:/.m2/repository/org/apache/httpcomponents/fluent-hc/4.2.1/fluent-hc-4.2.1.jar
[ERROR] urls[26] = file:/D:/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[27] = file:/D:/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by garrettheel** [comment]
Hi, is there any chance that you're using a version of moco > `0.9.2` (latest stable)? It seems that some APIs required for `moco-maven-plugin` have changed recently, but this should affect the latest snapshot for now.

**Comment by hanrw** [comment]
yes, i'm using the version of 0.9.2, and checked the code on https://github.com/dreamhead/moco, the code has changed.so i think the latest snapshot  is not available on the maven repository.

**Comment by garrettheel** [comment]
So it seems like the dep version range is picking up the new SNAPSHOT where I didn't expect it too.

For now, just add this to your `pom.xml` where you're using the plugin and it should solve it:

``` xml
<plugin>
  <artifactId>moco-maven-plugin</artifactId>
  <!-- ... -->
  <dependencies>
    <dependency>
      <groupId>com.github.dreamhead</groupId>
      <artifactId>moco-runner</artifactId>
      <version>0.9.2</version>
    </dependency>
  </dependencies>
</plugin>
```

**Comment by garrettheel** [comment]
Ok, I pushed up a fix to central that should fix this. Let me know if it solves your problem.

**Comment by hanrw** [comment]
Thanks, it's works now.
I just forked your project. if something wrong i will tell you then.
